name: terradue_snapista
channels:
  - anaconda
  - conda-forge
  - terradue
  - defaults
dependencies:
  - _libgcc_mutex
  - _openmp_mutex
  - affine
  - aiohttp
  - aiosignal
  - alsa-lib
  - asciitree
  - asf_search
  - async-timeout
  - asynctest
  - attr
  - attrs
  - backports
  - backports.zoneinfo
  - beautifulsoup4
  - blas
  - blinker
  - blosc
  - boost-cpp
  - branca
  - brotli
  - brotli-bin
  - brotlipy
  - bzip2
  - c-ares
  - ca-certificates
  - ca-certificates-cos6-x86_64
  - cachetools
  - cairo
  - certifi
  - cffi
  - cfitsio
  - charset-normalizer
  - click
  - click-plugins
  - cligj
  - cloudpickle
  - colorama
  - colorlog
  - copy-jdk-configs-cos6-x86_64
  - cryptography
  - curl
  - cycler
  - cytoolz
  - dask-core
  - dateparser
  - dbus
  - decorator
  - docopt
  - earthengine-api
  - earthpy
  - entrypoints
  - et_xmlfile
  - exceptiongroup
  - expat
  - fasteners
  - fftw
  - fiona
  - folium
  - font-ttf-dejavu-sans-mono
  - font-ttf-inconsolata
  - font-ttf-source-code-pro
  - font-ttf-ubuntu
  - fontconfig
  - fonts-conda-ecosystem
  - fonts-conda-forge
  - fonttools
  - freetype
  - freexl
  - frozenlist
  - fsspec
  - gconf2-cos6-x86_64
  - gcsfs
  - geojson
  - geomet
  - geopandas
  - geopandas-base
  - geos
  - geotiff
  - gettext
  - giflib
  - glib
  - glib-tools
  - google-api-core
  - google-api-python-client
  - google-auth
  - google-auth-httplib2
  - google-auth-oauthlib
  - google-cloud-core
  - google-cloud-storage
  - google-crc32c
  - google-resumable-media
  - googleapis-common-protos
  - grpc-cpp
  - grpcio
  - gst-plugins-base
  - gstreamer
  - hdf4
  - hdf5
  - html2text
  - httplib2
  - icu
  - idna
  - imagecodecs-lite
  - imageio
  - importlib-metadata
  - importlib_metadata
  - iniconfig
  - jack
  - java-1.7.0-openjdk-cos6-x86_64
  - jinja2
  - joblib
  - jpackage-utils-cos6-x86_64
  - jpeg
  - json-c
  - kealib
  - keyutils
  - kiwisolver
  - krb5
  - lcms2
  - ld_impl_linux-64
  - lerc
  - libabseil
  - libblas
  - libbrotlicommon
  - libbrotlidec
  - libbrotlienc
  - libcap
  - libcblas
  - libclang
  - libclang13
  - libcrc32c
  - libcups
  - libcurl
  - libdap4
  - libdb
  - libdeflate
  - libedit
  - libev
  - libevent
  - libexpat
  - libffi
  - libflac
  - libgcc-ng
  - libgdal
  - libgfortran-ng
  - libgfortran5
  - libglib
  - libgomp
  - libiconv
  - libjpeg-turbo-cos6-x86_64
  - libkml
  - liblapack
  - libllvm14
  - libnetcdf
  - libnghttp2
  - libnsl
  - libogg
  - libopenblas
  - libopus
  - libpng
  - libpq
  - libprotobuf
  - librttopo
  - libsndfile
  - libspatialindex
  - libspatialite
  - libsqlite
  - libssh2
  - libstdcxx-ng
  - libtiff
  - libtool
  - libudev1
  - libuuid
  - libvorbis
  - libwebp
  - libwebp-base
  - libxcb
  - libxkbcommon
  - libxml2
  - libxslt
  - libzip
  - libzlib
  - locket
  - lxml
  - lz4-c
  - mapclassify
  - markupsafe
  - matplotlib
  - matplotlib-base
  - msgpack-python
  - multidict
  - munch
  - munkres
  - mysql-common
  - mysql-libs
  - ncurses
  - networkx
  - nspr
  - nss
  - numcodecs
  - numpy
  - numpy-base
  - oauthlib
  - openjpeg
  - openpyxl
  - openssl
  - p11-kit-cos6-x86_64
  - p11-kit-trust-cos6-x86_64
  - packaging
  - pandas
  - partd
  - pcre
  - pillow
  - pip
  - pipreqs
  - pixman
  - pluggy
  - ply
  - poppler
  - poppler-data
  - portaudio
  - postgresql
  - proj
  - protobuf
  - psutil
  - pthread-stubs
  - pulseaudio
  - pyasn1
  - pyasn1-modules
  - pycparser
  - pyjwt
  - pyopenssl
  - pyparsing
  - pyproj
  - pyqt
  - pyqt5-sip
  - pysocks
  - pytest
  - python
  - python-dateutil
  - python-tzdata
  - python_abi
  - pytz
  - pytz-deprecation-shim
  - pyu2f
  - pywavelets
  - pyyaml
  - qt
  - qt-main
  - qt-webengine
  - rasterio
  - rasterstats
  - re2
  - readline
  - regex
  - requests
  - requests-oauthlib
  - rioxarray
  - rsa
  - rtree
  - scikit-image
  - scikit-learn
  - scipy
  - sentinelsat
  - setuptools
  - shapely
  - simplejson
  - sip
  - six
  - snap
  - snapista
  - snappy
  - snuggs
  - soupsieve
  - sqlite
  - threadpoolctl
  - tifffile
  - tiledb
  - tk
  - toml
  - tomli
  - toolz
  - tornado
  - tqdm
  - typing-extensions
  - typing_extensions
  - tzcode
  - tzdata
  - tzlocal
  - unicodedata2
  - uritemplate
  - urllib3
  - wheel
  - xarray
  - xcb-util
  - xcb-util-image
  - xcb-util-keysyms
  - xcb-util-renderutil
  - xcb-util-wm
  - xerces-c
  - xkeyboard-config
  - xorg-kbproto
  - xorg-libice
  - xorg-libsm
  - xorg-libx11
  - xorg-libxau
  - xorg-libxdmcp
  - xorg-libxext
  - xorg-libxrender
  - xorg-renderproto
  - xorg-xextproto
  - xorg-xproto
  - xyzservices
  - xz
  - yaml
  - yarg
  - yarl
  - zarr
  - zipp
  - zlib
  - zstd
  - pip:
      - gdal
      - jpy
