name: oiltanks
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - pip
  - gdal
  - pytorch
  - torchdata
  - google-cloud-storage
  - ipykernel
  - pip:
    - git+git://github.com/eogit/pyeo.git