name: sar
channels:
  - conda-forge
dependencies:
  - python
  - asf_search
  - ca-certificates
  - openssl
  - sentinelsat
  - certifi
  - colorlog
  - google-cloud-storage
  - geopandas
  - openpyxl
