name: Run Pytest Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Installing required ubuntu packages
      run: |
        sudo apt-get update
        sudo apt-get install jq

    - name: Getting Earth data username and password
      run: |
        if [ "$EARTHDATA_USERNAME" == "vardhan609@gmail.com" ]; then
          echo "username is correct"
          exit 0
        fi
        if [ "EARTHDATA_PASSWORD" == "Nani@351995"]; then
          echo "password is correct"
          exit 0
        fi
      env:
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
        EARTHDATA_PASSWORD: ${{ secrets.EARTHDATA_PASSWORD}}
    
    - name: Getting GCP service account key
      run: |
        echo "$SERVICE_ACC_KEY" > serice_acc_key.json
        SERVICE_ACC_KEY_PATH=$(realpath service_acc_key.json)
        PROJECT_ID=$(jq -r '.project_id' "$SERVICE_ACC_KEY_PATH")
        # Check if the variables are empty
        if [[ "$PROJECT_ID" == "gy7720" ]]; then
          echo "$SERVICE_ACC_KEY_PATH exists"
        fi
      env:
        SERVICE_ACC_KEY: ${{ secrets.GCP_SERVICE_ACC_KEY}}

    - name: Run tests     
      run: |
        pytest tests/run/test_*.py
