name: Run Pytest Workflow

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |     
        python -m pip install --upgrade pip
        pip install -r requirements.txt      
      
    - name: Run tests
      env:
        EARTHDATA_USERNAME: ${{ secrets.EARTHDATA_USERNAME }}
        EARTDATA_PASSWORD: ${{ secrets.EARTDATA_PASSWORD }}      
      run: |
        pytest tests/run/test_*.py
